### PR TITLE
map:build (edits) qt4cg/qtspecs#151

### PR DESCRIPTION
**Pull request by ChristianGruen**

### CODE REVIEW

**Review by michaelhkay — APPROVED** [review]
I believe the result of -005 is correct.

**Comment by ChristianGruen** [comment]
I believe `9` is correct:

```xquery
function($n) { $days => index-of($n) },
```

…will always be `3` for `Tuesday` and…

```xquery
let $days := ("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"),
```

…no matter in which order the items of `$days` will be passed on to `map:build`.

**Comment by michaelhkay** [comment]
Yes. I think I must have got the 36 result doing $fortnight => index-of.

**Comment by ChristianGruen** [comment]
@michaelhkay Is there still something I can do to finalize this pull request?

I tried to rewrite the example to yield `36`. This could be one option…

```xquery
let $days := ('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'),
    $fortnight := ($days, reverse($days))
return map:build(
  $fortnight,
  identity#1,
  function($n) { $fortnight => index-of($n) },
  function($a, $b) { head($a) * tail($b) }
)?Tuesday
```

…but I’m uncertain if that’s what you were thinking of?

**Comment by ChristianGruen** [comment]
Looks outdated.

**Pull request closed without merging**
