### PR TITLE
PR1068 Tests for proposed function graphemes

### PR DESCRIPTION
**Pull request by Arithmeticus**
First draft of a battery of tests for proposed function in PR https://github.com/qt4cg/qtspecs/pull/1068

### CODE REVIEW

**Review by ChristianGruen — CHANGES_REQUESTED** [review]
@Arithmeticus Thanks! Comments:

* In order to be considered, the new `graphemes.xml` file must be added to https://github.com/qt4cg/qt4tests/blob/master/catalog.xml
* It would be interesting to have tests for the `legacy` option.
* The following (and possibly other) test cases contain characters that are no valid XML 1.0 characters (e.g. `0x0001`):

```
graphemes-009
graphemes-010
graphemes-057
graphemes-058
graphemes-105
graphemes-106
graphemes-147
graphemes-148
graphemes-149
graphemes-150
graphemes-151
graphemes-152
graphemes-153
graphemes-154
graphemes-155
graphemes-156
graphemes-157
graphemes-158
graphemes-159
graphemes-160
graphemes-161
graphemes-162
graphemes-163
graphemes-164
graphemes-165
graphemes-166
graphemes-167
graphemes-168
graphemes-169
graphemes-170
graphemes-171
graphemes-172
graphemes-173
graphemes-174
graphemes-175
graphemes-176
graphemes-177
graphemes-178
graphemes-179
graphemes-180
graphemes-181
graphemes-182
graphemes-183
graphemes-184
graphemes-185
graphemes-186
graphemes-187
graphemes-188
graphemes-189
graphemes-190
graphemes-191
graphemes-192
graphemes-193
graphemes-194
graphemes-201
graphemes-202
graphemes-249
graphemes-250
graphemes-297
graphemes-298
graphemes-345
graphemes-346
graphemes-393
graphemes-394
graphemes-441
graphemes-442
graphemes-489
graphemes-490
graphemes-537
graphemes-538
graphemes-585
graphemes-586
graphemes-633
graphemes-634
graphemes-681
graphemes-682
graphemes-729
graphemes-730
graphemes-777
graphemes-778
graphemes-825
graphemes-826
graphemes-873
graphemes-874
graphemes-921
graphemes-922
graphemes-969
graphemes-970
graphemes-1017
graphemes-1018
graphemes-1065
graphemes-1066
graphemes-1113
graphemes-1114
```

**Comment by ChristianGruen** [comment]
Ideally, we can ensure that the added test cases will be *stable*, i.e., that the results won’t depend on (or change with) specific versions of ICU.

Our aim cannot be completeness. If we want to be pragmatic, we could focus on results that are generated by the basic BreakIterator implementation of an older version of the JDK (11 or 8) or an older version of the ICU.

**Comment by Arithmeticus** [comment]
Thanks, @ChristianGruen . I'll get to this next week. 

Current test is a simple XSLT I wrote to convert the current Unicode 15.1 test page into our test model. I think any future additions can be made judiciously by diffing Unicode version X tests against 15.1 tests.

Can you point me to places in the test suite that exemplify how control codepoints are best handled (i.e., non-XML1.0 but ok in XML 1.1)? I need examples for both input and output.

**Comment by michaelhkay** [comment]
There are examples of tests involving control characters at, for example, 

```
<test-case name="K-CodepointToStringFunc-8a">
         <description>Codepoint 8 is invalid in XML 1.0 but valid in XML 1.1. Test created according to bug issue 29405</description>
         <created by="Frans Englich" on="2007-11-26"/>
	 <modified by="Tim Mills" on="2016-04-28" change="See bug 29405" />
	 <modified by="Josh Spiegel" on="2016-04-28" change="See bug 29405" />
         <dependency type="xml-version" value="1.1" />
         <test>codepoints-to-string(8)</test>
         <result>
            <assert>string-to-codepoints($result) eq 8</assert>
         </result>
      </test-case>
```

These days you could use `char(8)` instead of `codepoints-to-string(8)`

**Comment by michaelhkay** [comment]
Another note about submitting tests:

(a) there's a schema for the testset files (catalog-schema.xsd) - validate before committing!

(b) we've published the Saxon test suite driver from time to time (perhaps not recently) - this enables you to run the tests in misc/CatalogCheck which perform further validation on the test suite.

**Comment by Arithmeticus** [comment]
@michaelhkay Thanks -- on (b) I'd like to see this incorporated into the to-do item assigned to @ndw :
>      * [ ] QT4CG-063-04: NW to try to add test review to the editorial meeting.

**Comment by Arithmeticus** [comment]
Latest commit addresses @ChristianGruen comments, except for legacy versus extended. Question raised at qtspecs whether legacy needs to be supported.

**Review by ChristianGruen — APPROVED** [review]

**Comment by ChristianGruen** [comment]
Looks good! I will merge the PR after qt4cg/qtspecs#1068 has been accepted.

**Pull request merged**
